CFLAGS = -g -Wall

objects = main.o fileIO.o userInterface.o degree.o departmentVector.o degreeVector.o stringFunctions.o  programCommand.o course.o courseBT.o coursePtrVector.o stringLinkedList.o student.o studentBT.o department.o

main : $(objects)
	gcc -o main $(objects)

CLEAN :
	rm *.o main
